spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  jpa:
    show-sql: true



server:
  tomcat:
    uri-encoding: UTF-8
  port: 8083

